steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '--build-arg'
          - TEST=false
          - '--target'
          - release
          - '--network'
          - host
          - '-t'
          - 'europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/prebid-server:latest'
          - .
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '--build-arg'
          - TEST=false
          - '--target'
          - release
          - '--network'
          - host
          - '-t'
          - 'europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/prebid-server:$TAG_NAME'
          - .
images:
    - europe-docker.pkg.dev/$PROJECT_ID/eu.gcr.io/prebid-server
